### ISSUE TITLE
Apply patches after related config file is created

### ISSUE THREAD

**Issue by Player505** [itzg/docker-mc-proxy#168]
Related to docker-minecraft-server issue [#2522](https://github.com/itzg/docker-minecraft-server/issues/2522)
Just thought I'd make an issue here too but from what I can see it's the same as the docker-minecraft-server issue.
I'm aware I can just mount the config file but would like to minimise the number of files needed to replicate on fresh system.

**docker-compose.yml**
```
version: "3.8"

services:
  proxy:
    image: itzg/bungeecord
    tty: true
    stdin_open: true
    ports:
      - "25565:25577"
      - "19132:19132/udp"
      - "24454:24454/udp"
    volumes:
     - ./velocity.toml:/server/velocity.toml
     - ./forwarding.secret:/server/forwarding.secret
    #- ./plugins:/plugins
     - ./patch.json:/server/patch.json
    environment:
      TYPE: VELOCITY
     #ICON: ~/server-icon.png
      MEMORY: 512m
      MODRINTH_PROJECTS: viaversion, viabackwards, viarewind
      MINECRAFT_VERSION: "1.20.1"
      PATCH_DEFINITIONS: /server/patch.json
    links:
      - limbo
    restart: always
```

**patch.json**
```
{
 "patches": [
    {
      "file": "/server/plugins/viaversion/config.yml",
      "ops": [
        {
          "$set": {
            "path": "$.max-pps",
            "value": -1
          }
        }
      ]
    }
  ]
}
```
