### ISSUE TITLE
Unable to write

### ISSUE THREAD

**Issue by mckoda09** [itzg/docker-mc-proxy#217]
```
Unable to write file '/grief/config/grief/server/plugins/limboauth/config.yml' (NoPermissions (FileSystemError): Error: EACCES: permission denied, mkdir '/grief/config/grief')
```

compose.yaml
```yaml
services:
  proxy:
    image: itzg/mc-proxy
    environment:
      EULA: TRUE
      TYPE: VELOCITY
      PLUGINS: |
        https://cdn.modrinth.com/data/4iChqdl8/versions/jO4WSjfa/limboauth-1.1.14.jar
        https://cdn.modrinth.com/data/TZOteSf2/versions/dbj8oOSx/limboapi-1.1.27.jar
    ports:
      - "25565:25565"
    volumes:
      - ./grief/config:/config:rw
      - proxy:/server
      - ./grief/server:/server:rw

volumes:
  proxy: {}
```
